// <auto-generated />
namespace RepositoryPattern.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class CreatePerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatePerson));
        
        string IMigrationMetadata.Id
        {
            get { return "201910221026303_CreatePerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
